📖 단위테스트 학습 1단계 - 야구게임
hoon25/java-playground-study pull request #3
Opened 2024-01-14 13:47 UTC by parkchoongho

2024-01-15 08:44 UTC, hoon25 commented on java-baseball-playground/src/test/java/study/StringTest.java
> +
`cmd`+`option`+`L` 버튼을 intellij에서 누르면 Formatting을 자동으로 해주는 단축키가 동작합니다!

2024-01-15 08:44 UTC, hoon25 commented on java-baseball-playground/src/test/java/study/SetTest.java
> +    void contains(int argument, boolean expected) {
step0 리뷰반영 👍

2024-01-15 08:44 UTC, hoon25 commented on java-baseball-playground/src/test/java/study/StringTest.java
> +    @Test
테스트 코드로 기능 구현을 해주셨네요! 
이것도 좋지만,

 이번 미션에서는 실제로 유저가 값을 콘솔로 입력하고, 그 값의 결과를 콘솔로 볼 수있는 어플리케이션을 만드는게 미션목표이니, 아래 코드처럼 동작하는 코드를 작성해보면 좋을 것 같아요!
아래는 예시일 뿐 작성은 자유롭게 해주시면 됩니다!
```
public class CalculatorApplication {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String value = scanner.nextLine();
        String[] values = value.split(" ");
        ... 코드구현
    }
}
```

2024-01-15 08:51 UTC, parkchoongho commented on java-baseball-playground/src/test/java/study/StringTest.java
> +    @Test
아하 그렇군요! 작업 반영해보겠습니다.

2024-01-15 08:59 UTC, parkchoongho commented on java-baseball-playground/src/test/java/study/StringTest.java
> +
꿀팁 감사합니다!

2024-01-15 08:59 UTC, hoon25 approved these changes

2024-01-15 09:00 UTC, hoon25 requested changes
PR Block 테스트

2024-01-20 19:06 UTC, hoon25 reviewed
2단계로 가기 전, 변경해보면 좋을 것 같은 내용 코멘트 남겨뒀어요!

2024-01-20 19:06 UTC, hoon25 commented on java-baseball-playground/src/main/java/Calculator.java
> +                if (calculation.equals("+")) result += Integer.parseInt(values[i]);
`Integer.parseInt(values[i]);` 같은 중복되는 코드를 줄일 수 있을 것 같아요

그리고 indent가 3칸인데 이것도 줄이는 노력을 해보면 좋을것 같습니다!

2024-01-20 19:06 UTC, hoon25 commented on java-baseball-playground/src/main/java/Calculator.java
> +                if (calculation.equals("/")) result /= Integer.parseInt(values[i]);
원하지 않는 연산기호가 오거나,  나머지가 존재하는 나눗셈일 경우 어떻게 처리를 해야할지 고민해보면 좋을 것 같아요.

연산자가 정해진 것들이라면 enum으로 두는건 어떨까요?

2024-01-20 19:06 UTC, hoon25 commented on java-baseball-playground/src/main/java/Calculator.java
> +        int result = 0;
초기값을 두려는 의도로 설정하신것 같군요.
할당하지 않았을때 각 타입의 초기값들도 알아두면 좋을것같습니다!

2024-01-21 21:31 UTC, parkchoongho commented on java-baseball-playground/src/main/java/Calculator.java
> +                if (calculation.equals("+")) result += Integer.parseInt(values[i]);
최대한 줄이려고 해봤는데, 쉽지 않네요 ㅠㅠ

2024-01-21 21:31 UTC, parkchoongho commented on java-baseball-playground/src/main/java/Calculator.java
> +                if (calculation.equals("/")) result /= Integer.parseInt(values[i]);
Enum 반영했습니다!

2024-01-21 21:31 UTC, parkchoongho commented on java-baseball-playground/src/main/java/Calculator.java
> +        int result = 0;
인스턴스 변수로 빼서 초기화 했습니다!

2024-01-21 21:37 UTC, parkchoongho commented
지금 보니 commit 남기는 컨벤션이 정해져있었네요 ㅠㅠ 다음 커밋부터 반영하겠습니다!

2024-01-22 17:28 UTC, hoon25 approved these changes
고생하셨습니다! 
1단계는 여기서 마무리하고 2단계로 넘어가면 될 것 같아요.

1단계 리뷰반영은 2단계 미션에서 같이 진행하는데, 편하게 해주시면 될 것 같습니다!
고생하셨습니다~!

2024-01-22 17:28 UTC, hoon25 commented on java-baseball-playground/src/main/java/Calculator.java
> +    private void setSymbol(String value) {
이 부분이 `CalucationSymbol` 함수로 넘어갈 수 있을거에요.

values()를 사용해서 CalucationSymbol값을 반환해주면되는데, 사실상 contains함수를 조금만 수정하면 될 것같네요!

2024-01-22 17:28 UTC, hoon25 commented on java-baseball-playground/src/main/java/Calculator.java
> +        int result = 0;
네넹 의도는 `int result;` `int result = 0;`는 동일하다는 의도를 전달하려고 했었어요!

js와 다르게 초기값이 0이거든요!

2024-01-22 17:28 UTC, hoon25 commented on java-baseball-playground/src/main/java/Calculator.java
> +        if (symbol == CalculationSymbol.PLUS) result += addition;
Google Java Format에서도 중괄호는 항상 있어야 한다고 가이드하고 있어요! 

참고) https://velog.io/@dbdb1114/WTC6W1-Google-Java-Style-Guide-feat.%EB%A7%90%ED%95%98%EB%8A%94-%EA%B0%90%EC%9E%90
의 4.1.1 참고링크입니다!

2024-01-22 17:28 UTC, hoon25 commented on java-baseball-playground/src/main/java/Calculator.java
> +                if (calculation.equals("+")) result += Integer.parseInt(values[i]);
자동차 경주-TDD 에서 유사한 문자열 덧셈 계산기 미션이 존재하니 그때 다시한번 트라이해보면 될 것 같아요!👍👍

2024-01-22 21:40 UTC, parkchoongho commented on java-baseball-playground/src/main/java/Calculator.java
> +    private void setSymbol(String value) {
symbol 관련 로직은 다 CalucationSymbol 쪽으로 몰 수 있겠네요! 감사합니다.

2024-01-22 21:41 UTC, parkchoongho commented on java-baseball-playground/src/main/java/Calculator.java
> +        if (symbol == CalculationSymbol.PLUS) result += addition;
자바 convention도 읽어봐야겠네요! 감사합니다.

2024-01-22 21:49 UTC, merged